// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtKG_dptXSpbuEVUlfJ62h4sRdOpIbQZc',
    appId: '1:105371146481:web:a8de202d527e257e7b3150',
    messagingSenderId: '105371146481',
    projectId: 'renthomeee',
    authDomain: 'renthomeee.firebaseapp.com',
    storageBucket: 'renthomeee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8_sSvrfGRPYj0GwCfgYPmMEg4AMx4-O0',
    appId: '1:105371146481:android:51bef6fc15bd26777b3150',
    messagingSenderId: '105371146481',
    projectId: 'renthomeee',
    storageBucket: 'renthomeee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ2BaQ4spAnbZpAwg4wcduzArCHvuLcXA',
    appId: '1:105371146481:ios:b8693541e84f07267b3150',
    messagingSenderId: '105371146481',
    projectId: 'renthomeee',
    storageBucket: 'renthomeee.appspot.com',
    iosBundleId: 'com.nitha.renthome.renthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ2BaQ4spAnbZpAwg4wcduzArCHvuLcXA',
    appId: '1:105371146481:ios:d819a5aefc6054027b3150',
    messagingSenderId: '105371146481',
    projectId: 'renthomeee',
    storageBucket: 'renthomeee.appspot.com',
    iosBundleId: 'com.nitha.renthome.renthome.RunnerTests',
  );
}
